# Generated by Django 4.2.15 on 2024-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
